# Generated by Django 5.0.4 on 2025-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('crop_type', models.CharField(max_length=100)),
                ('date_planted', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
