# Generated by Django 5.0.4 on 2025-10-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Labor', 'Labor'), ('Fertilizer', 'Fertilizer'), ('Seeds', 'Seeds'), ('Fuel', 'Fuel'), ('Machinery Repair', 'Machinery Repair'), ('Power', 'Power'), ('Misc', 'Miscellaneous')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fields.field')),
            ],
        ),
    ]
