# Generated by Django 5.0.4 on 2025-10-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_or_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='fields.field')),
            ],
        ),
    ]
