# Generated by Django 5.0.4 on 2025-10-22 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('Planting', 'Planting'), ('Weeding', 'Weeding'), ('Fertilizing', 'Fertilizing'), ('Irrigation', 'Irrigation'), ('Harvesting', 'Harvesting'), ('Spraying', 'Spraying')], max_length=50)),
                ('date', models.DateField()),
                ('worker_name', models.CharField(blank=True, max_length=100)),
                ('hours_spent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='fields.field')),
            ],
        ),
    ]
